# MIT License
# Copyright (C) 2020 Tymko Oleg <olegtymko@yandex.ru> and contributors
# All rights reserved.

name: Контроль качества
# Любой пуш и pr в проекте но с фильтром по основному проекту
on: [push, pull_request]
jobs:
  build:
    if: github.repository == 'Diversus23/color1c'
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true    
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    steps:
      # Загрузка проекта
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # Установка NodeJs

      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      - name: Извлечение имени текущей ветки
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
          
      # Сохраняем файл env.json с настройками среды
      - name: 'Create settings.json file'
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "settings.json"
          json: ${{ secrets.SETTINGS_JSON }}

      - name: Извлечение версии пакета
        shell: bash
        run: echo "##[set-output name=version;]`cat ./src/ExternalDataProcessors/РаботаСЦветами/ObjectModule.bsl | grep "Версия = " | sed 's|[^"]*"||' | sed -r 's/".+//'`"
        id: extract_version

      # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
      - name: Установка Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Установка Sonar-scanner
        uses: warchant/setup-sonar-scanner@v6

      # Анализ проекта в SonarQube (ветка)
      - name: Анализ в SonarQube (branch)
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        
        run: sonar-scanner
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
            -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}
            -Dsonar.projectVersion=${{ steps.extract_version.outputs.version }}

      # Анализ проекта в SonarQube (PR)
      # https://docs.sonarqube.org/latest/analysis/pull-request/
      - name: Анализ в SonarQube (pull-request)
        if: github.event_name == 'pull_request'
        run: sonar-scanner
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
            -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}